[package]
authors = ["Judge Maygarden <judge@jmaygarden.com>"]
description = "Serial Line Internet Protocol (SLIP) encoder/decoder"
edition = "2018"
license = "MIT"
name = "slip-codec"
version = "0.1.0"

[dependencies]
